package Ventanas;

import Clases.Alumno;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CargarAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargarAlumnos
     */
    public CargarAlumnos() {
        super("Formulario de Alumnos");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLLegajo = new javax.swing.JLabel();
        jTLegajo = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jBSalir = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLLegajo.setText("LEGAJO:");

        jTLegajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTLegajoKeyTyped(evt);
            }
        });

        jLApellido.setText("APELLIDO:");

        jTApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTApellidoKeyTyped(evt);
            }
        });

        jLNombre.setText("NOMBRE:");

        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guargar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLNombre)
                            .addGap(24, 24, 24)
                            .addComponent(jTNombre))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLLegajo)
                            .addGap(30, 30, 30)
                            .addComponent(jTLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLApellido)
                        .addGap(18, 18, 18)
                        .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBGuardar)
                .addGap(29, 29, 29)
                .addComponent(jBNuevo)
                .addGap(26, 26, 26)
                .addComponent(jBSalir)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTLegajo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTApellido)
                    .addComponent(jLApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBNuevo)
                    .addComponent(jBGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///---------BOTON SALIR---------
    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    ///---------BOTON NUEVO---------
    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        jTLegajo.setText("");
        jTApellido.setText("");
        jTNombre.setText("");
    }//GEN-LAST:event_jBNuevoActionPerformed

    ///---------BOTON GUARDAR---------
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        int ubi=Colegio.getAlumnos().size()+1;
        boolean rep=false;
        if(!rep){rep=verificarCampos(jTLegajo);}
        if(!rep){rep=verificarCampos(jTApellido);}
        if(!rep){rep=verificarCampos(jTNombre);}
        if(!rep){
            for (Map.Entry<Integer, Alumno> en : Colegio.getAlumnos().entrySet()) {
                Alumno alum = en.getValue();
                if(Integer.parseInt(jTLegajo.getText())==alum.getLegajo()){
                    rep=true;
                }
            }
            if(!rep){
                Colegio.getAlumnos().put(ubi, new Alumno(Integer.parseInt(jTLegajo.getText()),jTApellido.getText(),jTNombre.getText()));
                JOptionPane.showMessageDialog(null, "Cargado correctamente");
            }else{
                    JOptionPane.showMessageDialog(null, "Legajo repetido");
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private boolean verificarCampos(javax.swing.JTextField tx){
        if(tx.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Completar Campo");
            tx.requestFocus();
            return true;
        }else{return false;}
    }
    
    ///---------VERIFICAR CAMPO LEGAJO---------
    private void jTLegajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTLegajoKeyTyped
        if((evt.getKeyChar()<48||evt.getKeyChar()>57)&&evt.getKeyChar()!=8){
            JOptionPane.showMessageDialog(this, "Igresar solo numeros","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            jTLegajo.requestFocus();
        }
    }//GEN-LAST:event_jTLegajoKeyTyped

    ///---------VERIFICAR CAMPO APELLIDO---------
    private void jTApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoKeyTyped
        verificar(evt,jTApellido);
    }//GEN-LAST:event_jTApellidoKeyTyped

    ///---------VERIFICAR CAMPO NOMBRE---------
    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
        verificar(evt,jTNombre);
    }//GEN-LAST:event_jTNombreKeyTyped

    ///---------VERIFICAR CAMPO TEXTO REUTILIZAR CODIGO---------
    private void verificar(java.awt.event.KeyEvent evt,javax.swing.JTextField tx){
        if((evt.getKeyChar()<65||evt.getKeyChar()>90)&&(evt.getKeyChar()<97||evt.getKeyChar()>122)&&evt.getKeyChar()!=8&&evt.getKeyChar()!=32){
            JOptionPane.showMessageDialog(this, "Igresar solo letras","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            tx.requestFocus();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLLegajo;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTLegajo;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
