package Ventanas;

import Clases.Alumno;
import Clases.Materia;

/**
 *
 * @author Usuario
 */
public class Inscribir extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inscripcion
     */
    public Inscribir() {
        super("Formulario de Inscripción");
        initComponents();
        materiasCB();///---------PRECARGAR MATERIAS---------
        alumnosCB();///---------PRECARGAR ALUMNOS---------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLMateria = new javax.swing.JLabel();
        jCBMaterias = new javax.swing.JComboBox<>();
        jLAlumno = new javax.swing.JLabel();
        jCBAlumnos = new javax.swing.JComboBox<>();
        jBSalir = new javax.swing.JButton();
        jBInscribir = new javax.swing.JButton();

        jLMateria.setText("ELIJA UNA MATERIA:");

        jLAlumno.setText("ELIJA UN ALUMNO:");

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBInscribir.setText("inscribir");
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMateria)
                    .addComponent(jLAlumno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBInscribir)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMateria)
                    .addComponent(jCBMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAlumno)
                    .addComponent(jCBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBInscribir))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///---------BOTON SALIR--------
    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    ///---------BOTON INSCRIBIR--------
    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        Colegio.getAlumnos().get(jCBAlumnos.getSelectedIndex()+1).agregarMateria(Colegio.getMaterias().get(jCBMaterias.getSelectedIndex()+1));
    }//GEN-LAST:event_jBInscribirActionPerformed

    ///---------COMBO BOX MATERIAS--------
    private void materiasCB(){
        jCBMaterias.removeAllItems();
        for (Materia mat : Colegio.getMaterias().values()) {
            jCBMaterias.addItem(mat.getNombre());
        }
    }

    ///---------COMBO BOX ALUMNOS--------
    private void alumnosCB(){
        jCBAlumnos.removeAllItems();
        for (Alumno alum : Colegio.getAlumnos().values()) {
            jCBAlumnos.addItem(alum.getApellido()+" "+alum.getNombre()+" ("+alum.getLegajo()+")");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBAlumnos;
    private javax.swing.JComboBox<String> jCBMaterias;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLMateria;
    // End of variables declaration//GEN-END:variables
}
