package Ventanas;

import Clases.Alumno;
import Clases.Materia;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class MostrarMateriasAlumnosInscriptos extends javax.swing.JInternalFrame {

    /**
     * Creates new form MostrarMateriasAlumnosInscriptos
     */
    public MostrarMateriasAlumnosInscriptos() {
        super("Alumnos Inscriptos");
        initComponents();
        cargarCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAlumnos = new javax.swing.JLabel();
        jCBAlumnos = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jTCantidadMaterias = new javax.swing.JTextField();

        jLAlumnos.setText("Alumnos: ");

        jCBAlumnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBAlumnosItemStateChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jTDatos);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jTCantidadMaterias.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBSalir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jTCantidadMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLAlumnos)
                                .addGap(18, 18, 18)
                                .addComponent(jCBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBAlumnos)
                    .addComponent(jLAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTCantidadMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jCBAlumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBAlumnosItemStateChanged
        int index=jCBAlumnos.getSelectedIndex();
        if(index>0){
            Map<Integer,Materia> mat=null;
            String colum[]={"Codigo","Nombre","Año"};
            mat=Colegio.getAlumnos().get(index).getMaterias();
            int cantMat=Colegio.getAlumnos().get(index).catidadMaterias();
            jTCantidadMaterias.setText("Inscripto a "+cantMat+" materias");
            String datos[][]= new String[mat.size()][3];
            int i=0;
            for (Map.Entry<Integer, Materia> en : mat.entrySet()) {
                Materia materia = en.getValue();
                datos[i][0]=String.valueOf(materia.getIdMateria());
                datos[i][1]=materia.getNombre();
                datos[i][2]=String.valueOf(materia.getAnio());
                i++;
            }
            jTDatos.setModel(new DefaultTableModel(datos,colum));
        }else{
            jTCantidadMaterias.setText("");
            String colum[]={"Codigo","Nombre","Año"};
            jTDatos.setModel(new DefaultTableModel(null,colum));
        }
        
    }//GEN-LAST:event_jCBAlumnosItemStateChanged

    private void cargarCB(){
        jCBAlumnos.removeAllItems();
        jCBAlumnos.addItem("Seleccionar");
        for (Alumno alum : Colegio.getAlumnos().values()) {
            jCBAlumnos.addItem(alum.getApellido()+" "+alum.getNombre()+" ("+alum.getLegajo()+")");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBAlumnos;
    private javax.swing.JLabel jLAlumnos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTCantidadMaterias;
    private javax.swing.JTable jTDatos;
    // End of variables declaration//GEN-END:variables
}
